server.port=8080
spring.application.name=api-gateway

# ==========================================
# 1. Eureka Integration
# ==========================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password=
spring.data.redis.timeout=60000

# ==========================================
# 2. Gateway Discovery
# ==========================================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.default-filters[0]=AuthenticationFilter

# Auth Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# User Service
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**, /api/leaderboard/**, /api/notes/**

# Problem Service
spring.cloud.gateway.routes[2].id=problem-service
spring.cloud.gateway.routes[2].uri=lb://problem-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/problems/**

# Judge Service
spring.cloud.gateway.routes[3].id=judge-service
spring.cloud.gateway.routes[3].uri=lb://judge-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/submissions/**

spring.cloud.gateway.routes[4].id=ai-assist-service
spring.cloud.gateway.routes[4].uri=lb://ai-assist-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/ai-assist/**





# ==========================================
# 3. CORS Configuration
# ==========================================
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

# Monitoring
management.endpoints.web.exposure.include=health,info,metrics,prometheus,gateway
management.endpoint.gateway.enabled=true

jwt.expiration.ms=86400000
