
# Server & Discovery
server.port=8081
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:auth-service}

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Expiration
jwt.expiration.ms=86400000
jwt.refresh.expiration.ms=604800000

# Redis Configuration
spring.data.redis.host=redis
spring.data.redis.port=6379
# spring.data.redis.password=
spring.data.redis.timeout=60000

# Logging
logging.level.com.leetcode=DEBUG
logging.level.org.springframework.cloud=INFO
logging.level.org.springframework.security=DEBUG

# Actuator & Observability
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when-authorized
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# Flyway Migration Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

# OpenAPI / Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=false
